In [12]:
import torch
from torch import nn
from d2l import torch as d2l


def dropout_layer(X, dropout):
    assert 0 <= dropout <= 1
    # 在本情况中，所有元素都被丢弃
    if dropout == 1:
        return torch.zeros_like(X)
    # 在本情况中，所有元素都被保留
    if dropout == 0:
        return X

    # 在PyTorch中，对一个张量执行比较操作时
    # 会生成一个与原始张量形状相同的布尔型张量
    # .float()再将其转为数值
    mask = (torch.rand(X.shape) > dropout).float()
    print(torch.rand(X.shape) )
    print(torch.rand(X.shape)>dropout)
    print((torch.rand(X.shape)>dropout).float())
    return mask * X / (1.0 - dropout)

In [13]:
X = torch.arange(16,dtype=torch.float32).reshape(2,8)
print(X)
print('=======================================')
print(dropout_layer(X,0.5))
print('=======================================')
print(dropout_layer(X,0))
print('=======================================')
print(dropout_layer(X,1))


tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.]])
tensor([[0.3673, 0.0708, 0.0657, 0.9881, 0.3088, 0.2577, 0.1063, 0.4795],
        [0.5264, 0.6689, 0.5795, 0.1162, 0.5276, 0.5697, 0.6639, 0.8532]])
tensor([[False, False, False, False, False, False, False,  True],
        [False,  True,  True,  True,  True, False, False, False]])
tensor([[0., 0., 0., 0., 1., 1., 1., 0.],
        [0., 0., 1., 1., 0., 0., 1., 0.]])
tensor([[ 0.,  0.,  4.,  6.,  8., 10., 12.,  0.],
        [16.,  0., 20.,  0.,  0.,  0., 28., 30.]])
tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])
