# 总结
深度学习存储和操作数据的主要接口是张量（n维数组）。它提供了各种功能，包括基本数学运算、广播、索引、切片、内存节省和转换其他Python对象。

In [114]:
import torch
x = torch.arange(12)
x

# torch.xxx来赋值都是一个tensor
# x = torch.arange(12) //输入范围
# torch.ones/zeros/randn()// 输入维度
# torch.tensor([])//输入具体数值/python列表
# 每个tensor，也有自己的方法。reshape, shape，numel之类
# tensor之间，也可以按照元素来进行加减乘除/平方/求幂之类的运算。

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [115]:
x.shape

torch.Size([12])

获取张量tensor中的元素个数，number element。一维时与shape一样

In [116]:
x.numel()

12

In [117]:
x = x.reshape(2,6)
x

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

reshape时候，行/列只用指定一个。因为知道总数，另一个可以自动算出来。
**不指定的那个要填上-1**

In [119]:
#等价于如上
x = x.reshape(-1,6)
x


tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [88]:
x = x.reshape(2,-1)
x

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [120]:

#一个方括号一个维度，看第一个方括号到邻近的最后一个方括号有几个，就是几维
#如下，最外层的方括号，表示2个内层的
#次一层的表示3个内层的
#再次一层表示4个内层的
torch.zeros(2,3,4) ,torch.zeros((2,3,4))

#这两种写法一样

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]))

In [90]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [91]:
torch.randn(3,4)
#取随机值，应该时默认符合标准正态分布
#标准正态分布又称为u分布，是以0为均值、以1为标准差的正态分布，  记为N（0，1）。

tensor([[-0.5293, -0.5802, -0.2763,  0.6859],
        [-0.3453, -0.0986, -0.6928, -0.0976],
        [ 1.3500,  0.1541, -0.9752,  0.9533]])

In [92]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
#用python的列表来赋值

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [93]:
# 按元素操作
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x + y, x - y, x * y, x / y,x **y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [94]:
# 按元素操作，还包括，求幂
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [95]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
#dim=0,按行拼接（默认），=1，按列拼接
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [96]:
# 判断两个张量，可以得到布尔值的结果，相同为True，不用为False
X==Y
#下面结果显示，x与y只有两个相同

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [97]:
#对张量所有元素进行求和
X.sum()

tensor(66.)

In [98]:
a = torch.arange(3).reshape(3,1)
b = torch.arange(3).reshape(1,3)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1, 2]]))

In [99]:
# 广播机制，不同类型的矩阵相加，扩成同型矩阵
a+b

tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]])

In [100]:
# 切片和索引，切片就是另一种选取元素的方式
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
X,X[-1],X[1:3]
#-1选最后一个元素，因为是二维的，所以一个元素就是一个向量
#1:3选第二个和第三个元素
#感觉是不加 , 逗号 ，就默认是第一个维度，这里就是默认行

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [101]:
# 可对单个元素赋值
# 对第2行第3列的元素进行赋值
X[1,2]=99
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 99.,  7.],
        [ 8.,  9., 10., 11.]])

In [102]:
# 选中多行 多列可批量赋值
# 如下选中第一行和第二行，0：2,不包括第三行，相当于右边开区间
# 逗号分隔一个维度，逗号后面， ： ,此符号表示所有列
X[0:2,:]=77
X

tensor([[77., 77., 77., 77.],
        [77., 77., 77., 77.],
        [ 8.,  9., 10., 11.]])

In [103]:
# 节省点内存
# 因为深度学习跑模型每秒运算太大了，或许还有别的引用指向原内存

#起因
#因为python中如下写运算，Y会重新得到个内存
#id()，来获取y的地址
y=1
x=2
before=id(Y)
Y=X+Y
id(Y)==before
#会输出false，说明地址变了

False

In [104]:
#向下面这样写就不会变
before=id(Y)
Y[:]=X+Y
id(Y)==before

True

In [105]:
#这样也行
Y+=X
id(Y)==before

True

In [106]:
# 创建一个相似结构的tensor
# _like 表示和Y结构一样
# zeros表示元素为0
Z=torch.zeros_like(Y)
Z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [107]:
#pytorch的张量(tensor)转换为Numpy的张量(ndarry),很容易，反之也很容易
#如下，将ndarry->tensor
A = X.numpy()
B = torch.tensor(A)
type(A),type(B),A,B


(numpy.ndarray,
 torch.Tensor,
 array([[77., 77., 77., 77.],
        [77., 77., 77., 77.],
        [ 8.,  9., 10., 11.]], dtype=float32),
 tensor([[77., 77., 77., 77.],
         [77., 77., 77., 77.],
         [ 8.,  9., 10., 11.]]))

In [108]:
# 将大小为1的张量转换为python的标量
a = torch.tensor([3.5])
# a.item(),将a转为标量 , 后面两个就用的python的强转
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

#### numpy矩阵运算（求逆、行列式值、特征向量特征值、求解线性方程组）


In [109]:
import numpy as np
A=np.array([
    [3,4],
    [1,2]
])
#求逆矩阵
a=np.linalg.inv(A)
a

array([[ 1. , -2. ],
       [-0.5,  1.5]])

In [110]:
# 求行列式
a=np.linalg.det(A)
a

2.0000000000000004

In [111]:
#求特征值和特征向量
a=np.linalg.eig(A)
a

(array([4.56155281, 0.43844719]),
 array([[ 0.93153209, -0.84212294],
        [ 0.36365914,  0.5392856 ]]))

In [112]:
#线性方程组Ax=B求解
B=np.array([9,8])
x=np.linalg.solve(A,B)
x

array([-7. ,  7.5])

In [113]:
#矩阵转置
A,A.T

(array([[3, 4],
        [1, 2]]),
 array([[3, 1],
        [4, 2]]))